FROM darthjee/dev_alan_wake-base:0.1.0

WORKDIR /home/app/app
COPY --chown=app:app source/Gemfile* /home/app/app/
COPY --chown=app:app source/bower.json /home/app/app/

RUN bundle install
RUN bundle clean --force

USER app
RUN bower install
