version: '3'
services:
  dev_alan_wake_mysql:
    image: mysql:5.7
    container_name: dev_alan_wake_mysql
    env_file: .env.dev
    environment:
      MYSQL_ROOT_PASSWORD: alan_wake
    ports:
      - 127.0.0.1:$DEV_ALAN_WAKE_MYSQL_PORT:3306

  alan_wake_mysql:
    image: mysql:5.7
    container_name: alan_wake_mysql
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: alan_wake
    ports:
      - 127.0.0.1:$LOCAL_ALAN_WAKE_MYSQL_PORT:3306
    volumes:
      - ./mysql:/var/lib/mysql


  #################### Base  ####################

  base: &base
    image: darthjee/dev_alan_wake
    volumes:
      - ./source:/home/app/app
    links:
      - dev_alan_wake_mysql:mysql
    env_file: .env.dev


  base_build:
    <<: *base
    build:
      context: .
      dockerfile: Dockerfile.dev_alan_wake
    command: echo done

  production_base_build:
    image: darthjee/production_alan_wake
    env_file: .env.dev
    environment:
      RAILS_ENV: production
    build:
      context: .
      dockerfile: Dockerfile.production_alan_wake
    command: echo done
  #################### CONTAINERS ####################

  alan_wake_app:
    <<: *base
    container_name: alan_wake_app
    command: /bin/bash bin/server.sh
    depends_on: [base_build]
    ports:
      - 127.0.0.1:3000:3000
    environment:
      - RAILS_ENV=development
      - ALAN_WAKE_MYSQL_PORT=3306

  alan_wake_tests:
    <<: *base
    container_name: alan_wake_tests
    command: /bin/bash bin/tests.sh
    depends_on: [base_build]
    environment:
      - RAILS_ENV=test

  alan_wake_root:
    <<: *base
    user: root
    container_name: alan_wake_root
    command: /bin/bash
    depends_on: [base_build]

  alan_wake_production:
    env_file: .env.production
    container_name: alan_wake_production
    image: $PRODUCTION_IMAGE

  alan_wake:
    env_file: .env
    container_name: alan_wake
    image: darthjee/alan_wake
    links:
      - alan_wake_mysql:mysql
