FROM darthjee/dev_alan_wake-base:0.0.2

WORKDIR /home/app/app
COPY --chown=app:app source/Gemfile* /home/app/app/
COPY --chown=app:app source/bower.json /home/app/app/

# RUN bundle install

USER app
RUN bower install
